constants:
  sub_env: <%= ENV['KA_SUB_ENV']%>
  env_identifier: <%= ENV['ENV_IDENTIFIER'] %>
  cookie_domain: <%= ENV['KA_COOKIE_DOMAIN'] %>
  support_email: <%= ENV['KA_SUPPORT_EMAIL'] %>

  admin_basic_auth:
    username: <%= ENV['KA_ADMIN_BASIC_AUTH_USERNAME'] %>
    password: <%= ENV['KA_ADMIN_BASIC_AUTH_PASSWORD'] %>

  aws:
    region: <%= ENV['KA_DEFAULT_AWS_REGION']%>
    user:
      access_key: <%= ENV['KA_USER_AWS_ACCESS_KEY']%>
      secret_key: <%= ENV['KA_USER_AWS_SECRET_KEY']%>

  kms:
    login:
      arn: <%= ENV['KA_LOGIN_KMS_ARN']%>
      id: <%= ENV['KA_LOGIN_KMS_ID']%>
    api_key:
      arn: <%= ENV['KA_API_KEY_KMS_ARN']%>
      id: <%= ENV['KA_API_KEY_KMS_ID']%>

  secret_encryptor:
    cookie_secret_key: <%= ENV['KA_COOKIE_SECRET_KEY'] %>
    email_tokens_decriptor_key: <%= ENV['KA_EMAIL_TOKENS_DECRIPTOR_KEY'] %>
    generic_sha_key: <%= ENV['KA_GENERIC_SHA_KEY'] %>
    cache_data_sha_key: <%= ENV['KA_CACHE_DATA_SHA_KEY'] %>

  recaptcha:
    site_key: <%= ENV['KA_RECAPTCHA_SITE_KEY'] %>
    secret_key: <%= ENV['KA_RECAPTCHA_SECRET'] %>

  memcached:
    instances: <%= ENV['KA_MEMCACHED_INSTANCES'] %>

  redis:
    url: <%= ENV['KA_REDIS_ENDPOINT'] %>

  pepo_campaigns:
    api:
      key: <%= ENV['KA_CAMPAIGN_CLIENT_KEY']%>
      secret: <%= ENV['KA_CAMPAIGN_CLIENT_SECRET']%>
      base_url: <%= ENV['KA_CAMPAIGN_BASE_URL']%>
      version: 'v2'
    list_ids:
      master_list: <%= ENV['KA_CAMPAIGN_MASTER_LIST']%>

  saas_api:
    endpoint: '<%= ENV['KA_SAAS_API_ENDPOINT'] %>/'
    secret_key: <%= ENV['KA_SAAS_API_SECRET_KEY'] %>

  company_web:
    domain: <%= ENV['KA_CW_DOMAIN'] %>
