constants:
  sub_env: <%= ENV['KA_SUB_ENV']%>
  env_identifier: <%= ENV['ENV_IDENTIFIER'] %>
  cookie_domain: <%= ENV['KA_COOKIE_DOMAIN'] %>
  support_email: <%= ENV['KA_SUPPORT_EMAIL'] %>
  activate_test_economy_auth_token: <%= ENV['KA_ACTIVATE_TEST_ECONOMY_AUTH_TOKEN'] %>

  admin_basic_auth:
    username: <%= ENV['KA_ADMIN_BASIC_AUTH_USERNAME'] %>
    password: <%= ENV['KA_ADMIN_BASIC_AUTH_PASSWORD'] %>

  aws:
    region: <%= ENV['KA_DEFAULT_AWS_REGION']%>
    user:
      access_key: <%= ENV['KA_USER_AWS_ACCESS_KEY']%>
      secret_key: <%= ENV['KA_USER_AWS_SECRET_KEY']%>

  s3:
    domain: <%= ENV['KA_S3_DOMAIN']%>
    master_folder: <%= ENV['KA_S3_MASTER_FOLDER']%>
    private:
      access_key: <%= ENV['KA_S3_ACCESS_KEY']%>
      secret_key: <%= ENV['KA_S3_SECRET_KEY']%>
      analytics_bucket: <%= ENV['KA_S3_ANALYTICS_BUCKET']%>
      reports_bucket: <%= ENV['KA_S3_REPORTS_BUCKET']%>
      platform_usage_reports_folder: <%= ENV['KA_S3_REPORTS_PLATFORM_USAGE_FOLDER']%>
      analytics_graphs_folder: <%= ENV['KA_S3_ANALYTICS_GRAPHS_FOLDER']%>
    public:
      access_key: <%= ENV['KA_S3_PUBLIC_ACCESS_KEY']%>
      secret_key: <%= ENV['KA_S3_PUBLIC_SECRET_KEY']%>
      bucket: <%= ENV['KA_S3_PUBLIC_BUCKET']%>
      test_economy_qr_code_folder: <%= ENV['KA_S3_PUBLIC_TEST_ECONOMY_QR_CODE_FOLDER']%>

  kms:
    login:
      arn: <%= ENV['KA_LOGIN_KMS_ARN']%>
      id: <%= ENV['KA_LOGIN_KMS_ID']%>
    api_key:
      arn: <%= ENV['KA_API_KEY_KMS_ARN']%>
      id: <%= ENV['KA_API_KEY_KMS_ID']%>

  secret_encryptor:
    cookie_secret_key: <%= ENV['KA_COOKIE_SECRET_KEY'] %>
    email_tokens_decriptor_key: <%= ENV['KA_EMAIL_TOKENS_DECRIPTOR_KEY'] %>
    generic_sha_key: <%= ENV['KA_GENERIC_SHA_KEY'] %>
    cache_data_sha_key: <%= ENV['KA_CACHE_DATA_SHA_KEY'] %>
    token_demo_sha_key: <%= ENV['KA_TOKEN_DEMO_SHA_KEY'] %>

  recaptcha:
    site_key: <%= ENV['KA_RECAPTCHA_SITE_KEY'] %>
    secret_key: <%= ENV['KA_RECAPTCHA_SECRET'] %>

  memcached:
    instances: <%= ENV['KA_MEMCACHED_INSTANCES'] %>

  redis:
    url: <%= ENV['KA_REDIS_ENDPOINT'] %>

  pepo_campaigns:
    api:
      key: <%= ENV['KA_CAMPAIGN_CLIENT_KEY']%>
      secret: <%= ENV['KA_CAMPAIGN_CLIENT_SECRET']%>
      base_url: <%= ENV['KA_CAMPAIGN_BASE_URL']%>
      version: 'v2'
    list_ids:
      platform_user_list: <%= ENV['KA_CAMPAIGN_MASTER_LIST']%>
      ost_master_list: <%= ENV['KA_CAMPAIGN_OST_MASTER_LIST']%>

  saas_api:
    endpoint: <%= ENV['KA_SAAS_API_ENDPOINT'] %>
    secret_key: <%= ENV['KA_SAAS_API_SECRET_KEY'] %>

  company_web:
    domain: <%= ENV['KA_CW_DOMAIN'] %>

  usage_report_recipients:
    email_ids: <%= ENV['KA_USAGE_REPORT_RECIPIENTS_EMAIL_IDS'] %>

  jira:
    username: <%= ENV['KA_JIRA_USERNAME'] %>
    password: <%= ENV['KA_JIRA_PASSWORD'] %>
    site: <%= ENV['KA_JIRA_SITE'] %>
    auth_type: <%= ENV['KA_JIRA_AUTH_TYPE'] %>
    project_name: <%= ENV['KA_JIRA_PROJECT_NAME'] %>
    assignee_name: <%= ENV['KA_JIRA_ASSIGNEE_NAME'] %>

  pipedrive:
    api_token: <%= ENV['KA_OST_PD_API_TOKEN'] %>
    enterprise_user_id: <%= ENV['KA_OST_ENTERPRISE_PD_USER_ID'] %>
    business_user_id: <%= ENV['KA_OST_BUSINESS_PD_USER_ID'] %>
    enterprise_stage_id: <%= ENV['KA_OST_ENTERPRISE_PD_STAGE_ID'] %>
    business_stage_id: <%= ENV['KA_OST_BUSINESS_PD_STAGE_ID'] %>
    pipedrive_deal_enterprise_custom_field: <%= ENV['KA_PD_DEAL_ENTERPRISE_CUSTOM_FIELD'] %>
    pipedrive_deal_mobile_app_custom_field: <%= ENV['KA_PD_DEAL_MOBILE_APP_CUSTOM_FIELD'] %>

  demo_mappy_server:
    endpoint: <%= ENV['KA_DEMO_MAPPY_SERVER_API_ENDPOINT'] %>

  demo_app:
    ios_url: <%= ENV['KA_DEMO_IOS_APP_URL'] %>
    android_url: <%= ENV['KA_DEMO_ANDROID_APP_URL'] %>

  company_other_product_urls:
    view_root_url: <%= ENV['KA_VIEW_ROOT_URL'] %>
    ost_web_root_url: <%= ENV['KA_OST_WEB_ROOT_URL'] %>

  google:
    usage_report_spreadsheet_id: <%= ENV['USAGE_REPORT_SPREADSHEET_ID'] %>