invalid_api_params:
  http_code: 422
  code: "INVALID_REQUEST"
  message: "At least one parameter is invalid or missing. See err.error_data for more details."

unauthorized_access_response:
  http_code: 401
  code: "UNAUTHORIZED"
  message: "Unauthorized"

api_under_maintenance:
  http_code: 502
  code: "SERVICE_UNAVAILABLE"
  message: "Service Temporarily Unavailable"

recaptcha_fail:
  http_code: 422
  code: "INVALID_REQUEST"
  message: "Re-Captcha has failed. "

resource_not_found:
  http_code: 404
  code: "NOT_FOUND"
  message: "The requested resource could not be located."

no_client_associated:
  http_code: 422
  code: "UNPROCESSABLE_ENTITY"
  message: "No client is associated with this account. Please contact support."

client_inactive:
  http_code: 422
  code: "UNPROCESSABLE_ENTITY"
  message: "Client is not active. Please contact support."

client_not_found:
  http_code: 404
  code: "NOT_FOUND"
  message: "Client not found."

manager_inactive:
  http_code: 422
  code: "UNPROCESSABLE_ENTITY"
  message: "Manager is not active. Please contact support."

manager_not_found:
  http_code: 404
  code: "NOT_FOUND"
  message: "Manager not found."

token_not_found:
  http_code: 404
  code: "NOT_FOUND"
  message: "Token not found."

workflow_empty:
  http_code: 404
  code: "NOT_FOUND"
  message: "Token not found."

invalid_token_deployment_workflow_status:
  http_code: 404
  code: "NOT_FOUND"
  message: "Workflow status does not match the token deployment status."

client_manager_inactive:
  http_code: 422
  code: "UNPROCESSABLE_ENTITY"
  message: "You are no longer a part of this economy. Please contact your admin."

something_went_wrong:
  http_code: 422
  code: "INTERNAL_SERVER_ERROR"
  message: "Something went wrong."

already_associated:
  http_code: 422
  code: "UNPROCESSABLE_ENTITY"
  message: "already associated."

user_not_verified:
  http_code: 422
  code: "UNPROCESSABLE_ENTITY"
  message: "user not verified."

invalid_authenticity_token:
  http_code: 401
  code: "UNAUTHORIZED"
  message: "Session has expired. Please refresh your page."

data_validation_failed:
  http_code: 422
  code: "UNPROCESSABLE_ENTITY"
  message: "data validation failed."
