invalid_api_params:
  http_code: 422
  code: "INVALID_REQUEST"
  message: "At least one parameter is invalid or missing. See err.error_data for more details."

unauthorized_access_response:
  http_code: 401
  code: "UNAUTHORIZED"
  message: "Unauthorized"

unauthorized_to_perform_action:
  http_code: 401
  code: "UNAUTHORIZED"
  message: "Not authorised to perform this action"

token_deploy_not_allowed:
  http_code: 422
  code: "INVALID_REQUEST"
  message: "Token Deployment prerequists not completed"

unauthorized_to_access_main_env:
  http_code: 401
  code: "UNAUTHORIZED"
  message: "Unauthorized to access Main ENV"

api_under_maintenance:
  http_code: 502
  code: "SERVICE_UNAVAILABLE"
  message: "Service Temporarily Unavailable"

recaptcha_fail:
  http_code: 422
  code: "INVALID_REQUEST"
  message: "Re-Captcha has failed. "

client_already_initiated_rotate:
  http_code: 422
  code: "INVALID_REQUEST"
  message: "Looks like already key was rotated once. Please wait for buffer time before reinitiating"

resource_not_found:
  http_code: 404
  code: "NOT_FOUND"
  message: "The requested resource could not be located."

no_client_associated:
  http_code: 422
  code: "UNPROCESSABLE_ENTITY"
  message: "No client is associated with this account. Please <a href=\"https://help.ost.com/support/home\" target=\"_blank\">contact support</a>."

client_inactive:
  http_code: 422
  code: "UNPROCESSABLE_ENTITY"
  message: "Client is not active. Please <a href=\"https://help.ost.com/support/home\" target=\"_blank\">contact support</a>."

client_not_found:
  http_code: 404
  code: "NOT_FOUND"
  message: "Client not found."

manager_inactive:
  http_code: 422
  code: "UNPROCESSABLE_ENTITY"
  message: "Manager is not active. Please <a href=\"https://help.ost.com/support/home\" target=\"_blank\">contact support</a>."

manager_not_found:
  http_code: 404
  code: "NOT_FOUND"
  message: "Manager not found."

token_not_found:
  http_code: 404
  code: "NOT_FOUND"
  message: "Token not found."

token_not_setup:
  http_code: 422
  code: "UNPROCESSABLE_ENTITY"
  message: "Token not setup."

token_demo_already_setup:
  http_code: 422
  code: "UNPROCESSABLE_ENTITY"
  message: "Token demo has already been setup."

token_demo_setup_incomplete:
  http_code: 422
  code: "UNPROCESSABLE_ENTITY"
  message: "Token demo setup is not yet done."

token_demo_too_many_invites:
  http_code: 422
  code: "UNPROCESSABLE_ENTITY"
  message: "You have already invited 1000 Emails in last 30 days."

aux_chain_id_not_found:
  http_code: 404
  code: "NOT_FOUND"
  message: "Aux chain Id not found."

workflow_empty:
  http_code: 404
  code: "NOT_FOUND"
  message: "Token not found."

invalid_token_deployment_workflow_status:
  http_code: 404
  code: "NOT_FOUND"
  message: "Workflow status does not match the token deployment status."

client_manager_inactive:
  http_code: 422
  code: "UNPROCESSABLE_ENTITY"
  message: "You are no longer a part of this economy. Please contact your admin."

something_went_wrong:
  http_code: 422
  code: "INTERNAL_SERVER_ERROR"
  message: "Something went wrong. Please <a href=\"https://help.ost.com/support/home\" target=\"_blank\">contact support</a>."

already_associated:
  http_code: 422
  code: "UNPROCESSABLE_ENTITY"
  message: "already associated."

user_not_verified:
  http_code: 422
  code: "UNPROCESSABLE_ENTITY"
  message: "user not verified."

invalid_authenticity_token:
  http_code: 401
  code: "UNAUTHORIZED"
  message: "Session has expired. Please refresh your page."

data_validation_failed:
  http_code: 422
  code: "UNPROCESSABLE_ENTITY"
  message: "data validation failed."

grant_limit_reached:
  http_code: 422
  code: "INVALID_REQUEST"
  message: "OST-Test is granted only once every 24 hours. This error also comes up due to a metamask issue. Please try re-enabling the metamask browser extension and hit refresh."

request_not_xhr:
  http_code: 422
  code: "INVALID_REQUEST"
  message: "Request should be xhr"

mfa_mandatory_for_client:
  http_code: 422
  code: 'invalid'
  message: 'You have been whitelisted on Mainnet, please set up your <a href="/mfa">2FA</a> to proceed.'

error_in_issue_creation:
  http_code: 422
  code: 'UNPROCESSABLE_ENTITY'
  message: 'Could not create issue.'