prefixes:
  kit_saas: &kit_saas
    prefix: '%{kit_saas}_'
  kit: &kit
    prefix: '%{kit}_'
  saas: &saas
    prefix: '%{saas}_'
  kit_subenv: &kit_subenv
    prefix: '%{kit_subenv}_'
  saas_subenv: &saas_subenv
    prefix: '%{saas_subenv}_'
  kit_saas_subenv: &kit_saas_subenv
      prefix: '%{kit_saas_subenv}_'

keys:

  manager:
    details:
      key_template: 'm_d_%{id}'
      expiry_in_seconds: 86400
      <<: *kit
    secure_details:
      key_template: 'm_sd_%{id}'
      expiry_in_seconds: 86400
      <<: *kit

  client:
    details:
      key_template: 'c_d_%{id}'
      expiry_in_seconds: 86400
      <<: *kit
    whitelisting:
      key_template: 'c_wlsting_%{id}'
      expiry_in_seconds: 86400
      <<: *kit_saas_subenv
    api_credentials:
      key_template: 'c_ac_%{id}'
      expiry_in_seconds: 86400
      <<: *kit_saas_subenv

  client_manager:
    details:
      key_template: 'c_md_%{client_id}_%{manager_id}'
      expiry_in_seconds: 86400
      <<: *kit

  ost_price_points_default:
      details:
        key_template: 'c_oppd_def'
        expiry_in_seconds: 600
        <<: *kit

  token_management:
    details:
      key_template: 'c_tkn_%{client_id}'
      expiry_in_seconds: 86400
      <<: *kit_saas_subenv

  token_address:
    details:
      key_template: 'ta_%{token_id}'
      expiry_in_seconds: 86400
      <<: *kit_saas_subenv

  token_company_users:
      details:
        key_template: 'c_tcud_%{token_id}'
        expiry_in_seconds: 86400
        <<: *kit_saas_subenv

  chain_addresses:
      details:
        key_template: 'ch_addr_%{chain_id}'
        expiry_in_seconds: 86400
        <<: *kit_saas_subenv

  staker_whitelisted_address:
      details:
        key_template: 'c_swa_%{token_id}'
        expiry_in_seconds: 86400
        <<: *kit_saas_subenv

  ost_price_points:
    chain_specific:
      key_template: 'c_ost_pp_%{chain_id}'
      expiry_in_seconds: 86400
      <<: *kit_saas_subenv

  workflow_status:
    default:
      key_template: 'c_d_s_%{workflow_id}'
      expiry_in_seconds: 86400
      <<: *kit_saas_subenv

  workflow:
    default:
      key_template: 'c_w_f_%{id}'
      expiry_in_seconds: 86400
      <<: *kit_saas_subenv
    by_client:
      key_template: 'c_w_f_bc_%{client_id}'
      expiry_in_seconds: 86400
      <<: *kit_saas_subenv