invalid_client_id:
  parameter: 'client_id'
  code: 'invalid'
  message: 'Invalid client id'

invalid_r_t:
  parameter: 'r_t'
  code: 'invalid'
  message: 'The reset password link is either invalid or has expired. Please use Forgot Password to generate a new one.'

invalid_i_t:
  parameter: 'i_t'
  code: 'invalid'
  message: 'The invite link is either invalid or has expired.'

missing_password_auth_cookie_value:
  parameter: 'r_t'
  code: 'missing'
  message: 'Your session has expired. please refresh your page.'

email_not_allowed_for_dev_program:
  parameter: 'email'
  code: 'invalid'
  message: 'In order to access OST KIT, please send an email to support@ost.com'

email_not_registered:
  parameter: 'email'
  code: 'invalid'
  message: 'The email address you provided is not associated with an OST KIT‚ç∫ account. Please sign up.'

email_auto_blocked:
  parameter: 'email'
  code: 'invalid'
  message: 'Your password has been reset. Please use Forgot Password to access your account.'

email_inactive:
  parameter: 'email'
  code: 'invalid'
  message: 'The email address you provided is inactive. Please contact Support.'

missing_email:
  parameter: 'email'
  code: 'missing'
  message: 'email missing'

invalid_email_domain:
  parameter: 'domain'
  code: 'invalid'
  message: 'The email domain you entered is not valid.'

invalid_email:
  parameter: 'email'
  code: 'invalid'
  message: 'The email address you entered is not valid.'

unrecognized_email:
  parameter: 'email'
  code: 'invalid'
  message: 'This user is not registered or is blocked'

already_registered_email:
  parameter: 'email'
  code: 'invalid'
  message: 'This email address is already in use. Please try logging in.'

already_verified_email:
  parameter: 'email'
  code: 'invalid'
  message: 'This email address is already verified.'

password_incorrect:
  parameter: 'password'
  code: 'invalid'
  message: 'The password you entered is incorrect. Please try again.'

password_invalid:
  parameter: 'password'
  code: 'invalid'
  message: 'Password should be minimum 8 characters.'

password_same:
  parameter: 'password'
  code: 'invalid'
  message: 'Please use a new different password.'

confirm_password_invalid:
  parameter: 'password'
  code: 'invalid'
  message: 'Passwords do not match.'

missing_email:
  parameter: 'email'
  code: 'missing'
  message: 'missing email'

missing_password:
  parameter: 'password'
  code: 'missing'
  message: 'missing password'

missing_browser_user_agent:
  parameter: 'browser_user_agent'
  code: 'missing'
  message: 'missing browser_user_agent'

missing_cookie_value:
  parameter: 'cookie_value'
  code: 'missing'
  message: 'missing cookie_value'

missing_r_t:
  parameter: 'r_t'
  code: 'missing'
  message: 'missing reset_token'

missing_i_t:
  parameter: 'i_t'
  code: 'missing'
  message: 'missing invite_token'

missing_confirm_password:
  parameter: 'confirm_password'
  code: 'missing'
  message: 'missing confirm_password'

missing_manager_id:
  parameter: 'manager_id'
  code: 'missing'
  message: 'missing manager_id'

missing_client_id:
  parameter: 'client_id'
  code: 'missing'
  message: 'missing client_id'

missing_agreed_terms_of_service:
  parameter: 'agreed_terms_of_service'
  code: 'missing'
  message: 'Please read the Term & Conditions and Policy of Use before registration.'

invalid_agreed_terms_of_service:
  parameter: 'agreed_terms_of_service'
  code: 'invalid'
  message: 'Please read the Term & Conditions and Policy of Use before registration.'

invalid_page_no:
  parameter: 'page_no'
  code: 'invalid'
  message: 'invalid page_no'